version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/amazona
      - JWT_SECRET=somethingsecret
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - backend

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
